# fly.toml app configuration file generated for lafav-staticman on 2023-07-06T13:30:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lafav-staticman"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  NODE_ENV = "production"
